// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubny/lite-reader/internal/app/item (interfaces: Scraper)
//
// Generated by this command:
//
//	mockgen -destination=./app/item/scraper_mock.go -package=mocks -mock_names=Scraper=Scraper github.com/cubny/lite-reader/internal/app/item Scraper
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Scraper is a mock of Scraper interface.
type Scraper struct {
	ctrl     *gomock.Controller
	recorder *ScraperMockRecorder
	isgomock struct{}
}

// ScraperMockRecorder is the mock recorder for Scraper.
type ScraperMockRecorder struct {
	mock *Scraper
}

// NewScraper creates a new mock instance.
func NewScraper(ctrl *gomock.Controller) *Scraper {
	mock := &Scraper{ctrl: ctrl}
	mock.recorder = &ScraperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Scraper) EXPECT() *ScraperMockRecorder {
	return m.recorder
}

// Scrape mocks base method.
func (m *Scraper) Scrape(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scrape", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scrape indicates an expected call of Scrape.
func (mr *ScraperMockRecorder) Scrape(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrape", reflect.TypeOf((*Scraper)(nil).Scrape), ctx, url)
}
