version: '3.7'
services:
  lite-reader:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_PATH: /var/opt/lite-reader/agg.db
    ports:
      - "8080:3000"
    volumes:
        - ./data:/var/opt/lite-reader