GOBIN = $(GOPATH)/bin

help:
	@echo "Please use 'make <target>' where <target> is one of the following:"

	@echo "  docker-run         to run the app with Docker (docker-compose)."
	@echo "  run                to run the app without Docker (go run)."
	@echo "  build              to build the app without Docker (go build)."

	@echo "  pre-commit         to run essential checks before you would make a commit."
	@echo "  dev-dependencies   to install all required Go dev dependencies"
	@echo "  gomod              to run tidy you go.mod file and load vendor files."
	@echo "  update-mocks       to update mocks."
	@echo "  gci                to apply gci."

	@echo "  lint               to perform linting."

	@echo "  test               run all unit tests."
	@echo "  coverage-report    open coverage report generated by make test."

dev-dependencies: | $(GOBIN)/mockgen $(GOBIN)/gci $(GOBIN)/golangci-lint

.PHONY: run-dev
run-dev:
	HTTP_PORT=3000 DB_PATH=data/agg.db nodemon --watch './**/*.go' --signal SIGTERM --exec 'go' run cmd/main.go

.PHONY: run
run:
	CGO_ENABLED=0 GOOS=linux go run -mod=vendor ./cmd/main.go

.PHONY: docker-run
docker-run:
	docker-compose -f docker-compose.yaml build
	docker-compose -f docker-compose.yaml up

.PHONY: build
build:
	CGO_ENABLED=0 GOOS=linux go build -mod=vendor -a -installsuffix cgo -o lite-reader ./cmd/main.go

pre-commit: gomod update-mocks lint test


.PHONY: gomod
gomod:
	@go mod tidy
	@go mod vendor

$(GOBIN)/mockgen:
	@go install github.com/golang/mock/mockgen@v1.6.0
	@$(MAKE) gomod

update-mocks: | $(GOBIN)/mockgen
	@find ./internal/mocks ! -name 'definition.go' -type f -exec rm {} +
	GO111MODULE=on go generate -mod=vendor -tags=mocks ./...
	@$(MAKE) gci

.PHONY: test
test:
	@mkdir -p reports
	@go test -coverprofile=reports/codecoverage_all.cov ./... -mod=vendor -cover -race -p=4
	@go tool cover -func=reports/codecoverage_all.cov > reports/functioncoverage.out
	@go tool cover -html=reports/codecoverage_all.cov -o reports/coverage.html
	@echo "View report at $(PWD)/reports/coverage.html"
	@tail -n 1 reports/functioncoverage.out

.PHONY: coverage-report
coverage-report:
	@open reports/coverage.html

$(GOBIN)/gci:
	@go install github.com/daixiang0/gci@v0.3.3
	@$(MAKE) gomod

gci: | $(GOBIN)/gci
	@gci write --Section Standard --Section Default --Section "Prefix(github.com/cubny/lite-reader)"  $(shell ls  -d $(PWD)/*/ | grep -v vendor)

$(GOBIN)/golangci-lint:
	@curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin v1.56.1

.PHONY: lint
lint: | $(GOBIN)/golangci-lint
	golangci-lint run -v

.PHONY: ci-run
ci-run:
	docker-compose build
	docker-compose up

.PHONY: docs
docs:
	docker run -v $(CURDIR):/local -w /local  quay.io/goswagger/swagger generate spec -o ./docs/swagger.json
	docker run -v $(CURDIR):/local -w /local  quay.io/goswagger/swagger generate spec -o ./docs/swagger.yaml


APP          := lite-reader
VERSION      := $(shell git describe --tags --abbrev=0)
COMMIT       := $(shell git rev-parse --short HEAD)
BUILD_DATE   := `date +%FT%T%z`
PKG_LIST     := $(shell go list ./... | grep -v /vendor/)
DB_URL       := postgres://postgres:postgres@localhost/lite-reader_test?sslmode=disable
DEB_IMG_ARCH := amd64

export PGPASSWORD := postgres

.PHONY: \
	lite-reader \
	lite-reader-no-pie \
	linux-amd64 \
	linux-arm64 \
	linux-armv7 \
	linux-armv6 \
	linux-armv5 \
	linux-x86 \
	darwin-amd64 \
	darwin-arm64 \
	freebsd-amd64 \
	freebsd-x86 \
	openbsd-amd64 \
	openbsd-x86 \
	netbsd-x86 \
	netbsd-amd64 \
	windows-amd64 \
	windows-x86 \

lite-reader:
	@ CGO_ENABLED=0 go build -buildmode=pie -o $(APP) main.go

lite-reader-no-pie:
	@ go build -o $(APP) main.go

linux-amd64:
	@ CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o $(APP)-$@ main.go

linux-arm64:
	@ CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o $(APP)-$@ main.go

linux-armv7:
	@ CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o $(APP)-$@ main.go

linux-armv6:
	@ CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o $(APP)-$@ main.go

linux-armv5:
	@ CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -o $(APP)-$@ main.go

darwin-amd64:
	@ GOOS=darwin GOARCH=amd64 go build -o $(APP)-$@ main.go

darwin-arm64:
	@ GOOS=darwin GOARCH=arm64 go build -o $(APP)-$@ main.go

freebsd-amd64:
	@ CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o $(APP)-$@ main.go

openbsd-amd64:
	@ GOOS=openbsd GOARCH=amd64 go build -o $(APP)-$@ main.go

windows-amd64:
	@ GOOS=windows GOARCH=amd64 go build -o $(APP)-$@ main.go

build: linux-amd64 linux-arm64 linux-armv7 linux-armv6 linux-armv5 darwin-amd64 darwin-arm64 freebsd-amd64 openbsd-amd64 windows-amd64
