// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubny/lite-reader/internal/infra/http/api (interfaces: FeedService)
//
// Generated by this command:
//
//	mockgen -destination=./infra/http/api/feed_mock.go -package=mocks -mock_names=FeedService=FeedService github.com/cubny/lite-reader/internal/infra/http/api FeedService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	feed "github.com/cubny/lite-reader/internal/app/feed"
	item "github.com/cubny/lite-reader/internal/app/item"
)

// FeedService is a mock of FeedService interface.
type FeedService struct {
	ctrl     *gomock.Controller
	recorder *FeedServiceMockRecorder
	isgomock struct{}
}

// FeedServiceMockRecorder is the mock recorder for FeedService.
type FeedServiceMockRecorder struct {
	mock *FeedService
}

// NewFeedService creates a new mock instance.
func NewFeedService(ctrl *gomock.Controller) *FeedService {
	mock := &FeedService{ctrl: ctrl}
	mock.recorder = &FeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FeedService) EXPECT() *FeedServiceMockRecorder {
	return m.recorder
}

// AddFeed mocks base method.
func (m *FeedService) AddFeed(command *feed.AddFeedCommand) (*feed.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFeed", command)
	ret0, _ := ret[0].(*feed.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFeed indicates an expected call of AddFeed.
func (mr *FeedServiceMockRecorder) AddFeed(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFeed", reflect.TypeOf((*FeedService)(nil).AddFeed), command)
}

// DeleteFeed mocks base method.
func (m *FeedService) DeleteFeed(command *feed.DeleteFeedCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeed", command)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeed indicates an expected call of DeleteFeed.
func (mr *FeedServiceMockRecorder) DeleteFeed(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeed", reflect.TypeOf((*FeedService)(nil).DeleteFeed), command)
}

// FetchItems mocks base method.
func (m *FeedService) FetchItems(arg0 int) ([]*item.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchItems", arg0)
	ret0, _ := ret[0].([]*item.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchItems indicates an expected call of FetchItems.
func (mr *FeedServiceMockRecorder) FetchItems(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchItems", reflect.TypeOf((*FeedService)(nil).FetchItems), arg0)
}

// ListFeeds mocks base method.
func (m *FeedService) ListFeeds(UserID int) ([]*feed.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeeds", UserID)
	ret0, _ := ret[0].([]*feed.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeeds indicates an expected call of ListFeeds.
func (mr *FeedServiceMockRecorder) ListFeeds(UserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeeds", reflect.TypeOf((*FeedService)(nil).ListFeeds), UserID)
}
