// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubny/lite-reader/internal/infra/http/api (interfaces: FolderService)
//
// Generated by this command:
//
//	mockgen -destination=./infra/http/api/folder_mock.go -package=mocks -mock_names=FolderService=FolderService github.com/cubny/lite-reader/internal/infra/http/api FolderService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	folder "github.com/cubny/lite-reader/internal/app/folder"
)

// FolderService is a mock of FolderService interface.
type FolderService struct {
	ctrl     *gomock.Controller
	recorder *FolderServiceMockRecorder
	isgomock struct{}
}

// FolderServiceMockRecorder is the mock recorder for FolderService.
type FolderServiceMockRecorder struct {
	mock *FolderService
}

// NewFolderService creates a new mock instance.
func NewFolderService(ctrl *gomock.Controller) *FolderService {
	mock := &FolderService{ctrl: ctrl}
	mock.recorder = &FolderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FolderService) EXPECT() *FolderServiceMockRecorder {
	return m.recorder
}

// AddFolder mocks base method.
func (m *FolderService) AddFolder(command *folder.AddFolderCommand) (*folder.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFolder", command)
	ret0, _ := ret[0].(*folder.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFolder indicates an expected call of AddFolder.
func (mr *FolderServiceMockRecorder) AddFolder(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFolder", reflect.TypeOf((*FolderService)(nil).AddFolder), command)
}

// DeleteFolder mocks base method.
func (m *FolderService) DeleteFolder(command *folder.DeleteFolderCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", command)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *FolderServiceMockRecorder) DeleteFolder(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*FolderService)(nil).DeleteFolder), command)
}

// GetFolder mocks base method.
func (m *FolderService) GetFolder(command *folder.GetFolderCommand) (*folder.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolder", command)
	ret0, _ := ret[0].(*folder.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolder indicates an expected call of GetFolder.
func (mr *FolderServiceMockRecorder) GetFolder(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolder", reflect.TypeOf((*FolderService)(nil).GetFolder), command)
}

// ListFolders mocks base method.
func (m *FolderService) ListFolders(userID int) ([]*folder.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolders", userID)
	ret0, _ := ret[0].([]*folder.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFolders indicates an expected call of ListFolders.
func (mr *FolderServiceMockRecorder) ListFolders(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolders", reflect.TypeOf((*FolderService)(nil).ListFolders), userID)
}

// RenameFolder mocks base method.
func (m *FolderService) RenameFolder(command *folder.RenameFolderCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameFolder", command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameFolder indicates an expected call of RenameFolder.
func (mr *FolderServiceMockRecorder) RenameFolder(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameFolder", reflect.TypeOf((*FolderService)(nil).RenameFolder), command)
}

// ReorderFolder mocks base method.
func (m *FolderService) ReorderFolder(command *folder.ReorderFolderCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderFolder", command)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderFolder indicates an expected call of ReorderFolder.
func (mr *FolderServiceMockRecorder) ReorderFolder(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderFolder", reflect.TypeOf((*FolderService)(nil).ReorderFolder), command)
}
