// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubny/lite-reader/internal/infra/http/api (interfaces: ItemService)
//
// Generated by this command:
//
//	mockgen -destination=./infra/http/api/item_mock.go -package=mocks -mock_names=ItemService=ItemService github.com/cubny/lite-reader/internal/infra/http/api ItemService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	item "github.com/cubny/lite-reader/internal/app/item"
	gomock "go.uber.org/mock/gomock"
)

// ItemService is a mock of ItemService interface.
type ItemService struct {
	ctrl     *gomock.Controller
	recorder *ItemServiceMockRecorder
	isgomock struct{}
}

// ItemServiceMockRecorder is the mock recorder for ItemService.
type ItemServiceMockRecorder struct {
	mock *ItemService
}

// NewItemService creates a new mock instance.
func NewItemService(ctrl *gomock.Controller) *ItemService {
	mock := &ItemService{ctrl: ctrl}
	mock.recorder = &ItemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ItemService) EXPECT() *ItemServiceMockRecorder {
	return m.recorder
}

// DeleteFeedItems mocks base method.
func (m *ItemService) DeleteFeedItems(arg0 *item.DeleteFeedItemsCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeedItems", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeedItems indicates an expected call of DeleteFeedItems.
func (mr *ItemServiceMockRecorder) DeleteFeedItems(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeedItems", reflect.TypeOf((*ItemService)(nil).DeleteFeedItems), arg0)
}

// GetFeedItems mocks base method.
func (m *ItemService) GetFeedItems(arg0 *item.GetFeedItemsCommand) ([]*item.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedItems", arg0)
	ret0, _ := ret[0].([]*item.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedItems indicates an expected call of GetFeedItems.
func (mr *ItemServiceMockRecorder) GetFeedItems(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedItems", reflect.TypeOf((*ItemService)(nil).GetFeedItems), arg0)
}

// GetStarredItems mocks base method.
func (m *ItemService) GetStarredItems() ([]*item.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarredItems")
	ret0, _ := ret[0].([]*item.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarredItems indicates an expected call of GetStarredItems.
func (mr *ItemServiceMockRecorder) GetStarredItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarredItems", reflect.TypeOf((*ItemService)(nil).GetStarredItems))
}

// GetStarredItemsCount mocks base method.
func (m *ItemService) GetStarredItemsCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarredItemsCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarredItemsCount indicates an expected call of GetStarredItemsCount.
func (mr *ItemServiceMockRecorder) GetStarredItemsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarredItemsCount", reflect.TypeOf((*ItemService)(nil).GetStarredItemsCount))
}

// GetUnreadItems mocks base method.
func (m *ItemService) GetUnreadItems() ([]*item.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadItems")
	ret0, _ := ret[0].([]*item.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadItems indicates an expected call of GetUnreadItems.
func (mr *ItemServiceMockRecorder) GetUnreadItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadItems", reflect.TypeOf((*ItemService)(nil).GetUnreadItems))
}

// GetUnreadItemsCount mocks base method.
func (m *ItemService) GetUnreadItemsCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadItemsCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadItemsCount indicates an expected call of GetUnreadItemsCount.
func (mr *ItemServiceMockRecorder) GetUnreadItemsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadItemsCount", reflect.TypeOf((*ItemService)(nil).GetUnreadItemsCount))
}

// ReadFeedItems mocks base method.
func (m *ItemService) ReadFeedItems(arg0 *item.ReadFeedItemsCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFeedItems", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadFeedItems indicates an expected call of ReadFeedItems.
func (mr *ItemServiceMockRecorder) ReadFeedItems(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFeedItems", reflect.TypeOf((*ItemService)(nil).ReadFeedItems), arg0)
}

// UnreadFeedItems mocks base method.
func (m *ItemService) UnreadFeedItems(arg0 *item.UnreadFeedItemsCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadFeedItems", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnreadFeedItems indicates an expected call of UnreadFeedItems.
func (mr *ItemServiceMockRecorder) UnreadFeedItems(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadFeedItems", reflect.TypeOf((*ItemService)(nil).UnreadFeedItems), arg0)
}

// UpdateItem mocks base method.
func (m *ItemService) UpdateItem(arg0 *item.UpdateItemCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *ItemServiceMockRecorder) UpdateItem(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*ItemService)(nil).UpdateItem), arg0)
}

// UpsertItems mocks base method.
func (m *ItemService) UpsertItems(command *item.UpsertItemsCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertItems", command)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertItems indicates an expected call of UpsertItems.
func (mr *ItemServiceMockRecorder) UpsertItems(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertItems", reflect.TypeOf((*ItemService)(nil).UpsertItems), command)
}
