<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<title>LiteReader</title>

	<script type="text/javascript" src="public/javascripts/jquery.js"></script>
	<script type="text/javascript" src="public/javascripts/jquery.ui.all.js"></script>
	<script type="text/javascript" src="public/javascripts/jquery.layout.js"></script>
   <link href="public/stylesheets/main.css" media="screen" rel="stylesheet" type="text/css" />
   <link href="public/stylesheets/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" />

	<script type="text/javascript">

	var myLayout; // a var is required because this page utilizes: myLayout.allowOverflow() method
	var myLayout1; // a var is required because this page utilizes: myLayout.allowOverflow() method

	$(document).ready(function () {
     $('body').layout({
       north:{
        resizable:false,
        closable:false,
        size:"auto",
        spacing_open:0
       },
       center:{
         size:250,
         spacing_closed:0,
       }
   });
     $('body > .ui-layout-center').layout({
        south:{
          size:250,
        }
     });
     $(document).click(hideAddFeed);
     $('#addfeed > *').click(showAddFeed);


     
   });
   function getDesc(id){
    $.getJSON('?index/getdesc/'+id,function(data){
      if(data.desc==null){
        $("#south").html($('<a href="'+data.link+'"/>').html(data.title));
      }else{
        $("#south").html(data.desc);
      }
    });
   }

   function getItems(id){
    $.getJSON('?index/getitems/'+id,function(data){
       $("#items").html("");
       $.each(data, function(i,item){
          $('<li/>').html($('<a href="javascript:getDesc('+item.id+')" />').html(item.title)).appendTo("#items");
      })
    })
   }
   function urlencode(s) {
     s = encodeURIComponent(s);
     return s.replace(/~/g,'%7E').replace(/%20/g,'+');
   }

   function addFeed(url){
    $.getJSON('?index/add/'+urlencode(url),function(data){
       var container=$(".ul-layout-west ul");
       container.html("");
       $.each(data, function(i,feed){
          $('<li/>').html($('<a href="javascript:getItems('+feed.id+')" />').html(feed.title)).appendTo(container);
      })
    })
   }
 
   function showAddFeed(e){
     e.stopPropagation();
     var aButton=$("#addfeed a");
     var aInput=$("#urlToAdd");
     aInput.removeClass('ui-state-error');
     aButton.parent().animate({width:"230px"},500,null,function(e){
            aInput.show();
            aButton.unbind('click');
            aButton.click(function(e){
              e.stopPropagation();
              var bValid = true;
				  aInput.removeClass('ui-state-error');
              bValid = bValid && checkLength(aInput,"password",10,255);
              bValid = bValid && checkRegexp(aInput,/(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/i,"Please Enter a Valid Url.");
              if(bValid){
                addFeed(aInput.val());
                aInput.val("");
                hideAddFeed();
              }
              
            });
     });
   }
   function hideAddFeed(){
     var aButton=$("#addfeed a");
     var aInput=$("#urlToAdd");
     aInput.hide();
     aButton.parent().animate({width:"60px"},300,null,function(){
       aButton.unbind('click');
       $('#addfeed > *').click(showAddFeed);
     });
   }
   function checkLength(o,n,min,max) {
     if ( o.val().length > max || o.val().length < min ) {
       o.addClass('ui-state-error');
       alert("Length of " + n + " must be between "+min+" and "+max+".");
       return false;
     } else {
       return true;
     }
   }

   function checkRegexp(o,regexp,n) {
     if ( !( regexp.test( o.val() ) ) ) {
       o.addClass('ui-state-error');
       alert(n);
       return false;
     } else {
       return true;
     }
   }


	</script>
</head>

<body>
   <div id="toolbar" class="ui-layout-north">
      <ul>
        <li id="addfeed" class="button">
            <input type="text" id="urlToAdd" style="display:none">
            <a href="#">
              <span class="add">Feed</span>
            </a>
        </li>
      </ul>
    </div>
    <div class="ui-layout-west">
      <ul>
      <?php foreach($feeds as $feed): ?>
        <li><a href="javascript:getItems(<?php echo $feed->id ?>)"><?php echo $feed->title; ?></a></li>
      <?php endforeach; ?>
     </ul>
    </div>
    <div id="content" class="ui-layout-center">
      <div class="ui-layout-center">
          <ul id="items">
          </ul>
      </div>
      <div id="south" class="ui-layout-south">
      </div>
    </div>

</body>
</html>
