<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<title>LiteReader</title>

	<script type="text/javascript" src="public/javascripts/jquery.js"></script>
	<script type="text/javascript" src="public/javascripts/jquery.ui.all.js"></script>
	<script type="text/javascript" src="public/javascripts/jquery.layout.js"></script>
	<script type="text/javascript" src="public/javascripts/jquery.cookie.js"></script>
	<script type="text/javascript" src="public/javascripts/main.js"></script>
   <link href="public/stylesheets/main.css" media="screen" rel="stylesheet" type="text/css" />
   <link href="public/stylesheets/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" />

	<script type="text/javascript">
	</script>
</head>

<body>
   <div id="toolbar" class="ui-layout-north">
      <ul>
        <li id="addfeed" class="button">
            <input type="text" id="urlToAdd" style="display:none">
            <a href="#">
              <span class="add">Feed</span>
            </a>
        </li>
      </ul>
    </div>
    <div class="ui-layout-west" id="feeds">
      <ul>
      <?php foreach($feeds as $feed): ?>
      <li id="<?php echo $feed->id?>"><div class="feedtitle"><?php echo $feed->title?></div><div class="count">(<span><?php echo $feed->unread; ?></span>)</div></li>
      <?php endforeach; ?>
     </ul>
    </div>
    <div id="content" class="ui-layout-center">
      <div class="ui-layout-north">
          <div id="feedbar">
              <div id="title"></div>
              <div id="actions">
                  <div class="update">update</div>
                  <div class="remove">remove</div>
              </div>
          </div>
      </div>
      <div id="msg">loading</div>
      <div class="ui-layout-center">
          <ul id="items">
          </ul>
      </div>
      <div id="south" class="ui-layout-south">
      </div>
    </div>

</body>
</html>
