<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>LiteReader</title>
  <link href="css/main.css,jquery-ui.css" media="screen" rel="stylesheet" type="text/css" />
  <link href='http://fonts.googleapis.com/css?family=Raleway:200' rel='stylesheet' type='text/css'>
	<script type="text/javascript">
	</script>
</head>

<body>

    <div class="ui-layout-west" id="feeds">
   <div id="toolbar" class="ui-layout-north">
        <div id="addfeed" class="button">
            <input type="text" id="urlToAdd" style="display:none">
            <a href="#">
              <span class="add">Feed</span>
            </a>
        </div>
    </div>
      <ul>
        <li class="feeds-actions">
            <div id="update-all">update all</div>
        </li>

      <?php foreach($feeds as $feed): ?>
        <li class="feed" id="<?php echo $feed->id?>">
            <?php $parsed = parse_url($feed->link); ?>
          <div class="count"><?php echo $feed->unread>0?"<span>".$feed->unread."</span>":""; ?></div>            
          <img src="http://g.etfv.co/<?php echo $feed->url; ?>">
          <div class="feedtitle"><?php echo $feed->title?></div>
        </li>
      <?php endforeach; ?>
     </ul>
    </div>
    <div id="content" class="ui-layout-center">
      <div class="ui-layout-north">
          <div id="feedbar">
              <div id="title"></div>
              <div id="actions">
                  <div class="action update">update</div>
                  <div id="mark-read-all" class="action markread">Read All</div>
                  <div id="mark-unread-all" class="action markread">Unread All</div>
                  <div class="action remove">remove</div>
              </div>
          </div>
      </div>
      <div id="msg">loading</div>
      <div class="ui-layout-center">
          <ul id="items">
          </ul>
      </div>
    </div>

<script type="text/template" id="item-template">
<li id={0}>
<div class="title"><span>{1}</span><a href="{3}" target="blank" class="item-link">link</a></div>
    <div class="desc">{2}</div>
</li>
</script>
</body>
<script type="text/javascript" src="javascript/jquery.js,jquery.ui.all.js,jquery.layout.js,jquery.cookie.js,jquery.scrollTo.min.js,utils.js,feeds.js,items.js,stage.js,main.js"></script>
</html>
