// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubny/lite-reader/internal/app/folder (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=./app/folder/repo_mock.go -package=mocks -mock_names=Repository=Repository github.com/cubny/lite-reader/internal/app/folder Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	folder "github.com/cubny/lite-reader/internal/app/folder"
)

// Repository is a mock of Repository interface.
type Repository struct {
	ctrl     *gomock.Controller
	recorder *RepositoryMockRecorder
	isgomock struct{}
}

// RepositoryMockRecorder is the mock recorder for Repository.
type RepositoryMockRecorder struct {
	mock *Repository
}

// NewRepository creates a new mock instance.
func NewRepository(ctrl *gomock.Controller) *Repository {
	mock := &Repository{ctrl: ctrl}
	mock.recorder = &RepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Repository) EXPECT() *RepositoryMockRecorder {
	return m.recorder
}

// AddFolder mocks base method.
func (m *Repository) AddFolder(arg0 *folder.Folder) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFolder", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFolder indicates an expected call of AddFolder.
func (mr *RepositoryMockRecorder) AddFolder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFolder", reflect.TypeOf((*Repository)(nil).AddFolder), arg0)
}

// DeleteFolder mocks base method.
func (m *Repository) DeleteFolder(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *RepositoryMockRecorder) DeleteFolder(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*Repository)(nil).DeleteFolder), id)
}

// GetFolder mocks base method.
func (m *Repository) GetFolder(id int) (*folder.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolder", id)
	ret0, _ := ret[0].(*folder.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolder indicates an expected call of GetFolder.
func (mr *RepositoryMockRecorder) GetFolder(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolder", reflect.TypeOf((*Repository)(nil).GetFolder), id)
}

// ListFolders mocks base method.
func (m *Repository) ListFolders(userID int) ([]*folder.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolders", userID)
	ret0, _ := ret[0].([]*folder.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFolders indicates an expected call of ListFolders.
func (mr *RepositoryMockRecorder) ListFolders(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolders", reflect.TypeOf((*Repository)(nil).ListFolders), userID)
}

// RenameFolder mocks base method.
func (m *Repository) RenameFolder(id int, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameFolder", id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameFolder indicates an expected call of RenameFolder.
func (mr *RepositoryMockRecorder) RenameFolder(id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameFolder", reflect.TypeOf((*Repository)(nil).RenameFolder), id, name)
}

// ReorderFolder mocks base method.
func (m *Repository) ReorderFolder(id, position int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderFolder", id, position)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderFolder indicates an expected call of ReorderFolder.
func (mr *RepositoryMockRecorder) ReorderFolder(id, position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderFolder", reflect.TypeOf((*Repository)(nil).ReorderFolder), id, position)
}
